version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: online_learning
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=learning_db
      - DB_USERNAME=ol_user
      - DB_PASSWORD=ol_password
    volumes:
      - .:/var/www
    # command: sh -c "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000"
    command: sh -c "php artisan serve --host=0.0.0.0 --port=8000"
    

  db:
    image: mysql:8.0
    container_name: mysql_ol_db
    environment:
      MYSQL_DATABASE: learning_db
      MYSQL_USER: ol_user
      MYSQL_PASSWORD: ol_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
